"""init

Revision ID: 3ef823c5b062
Revises: 
Create Date: 2026-08-18 09:39:21.172323

"""
from alembic import op
import sqlalchemy as sa


revision = '3ef823c5b062'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('export_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('draft_id', sa.String(length=64), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_log_draft_id'), 'export_log', ['draft_id'], unique=False)
    op.create_table('reference_material',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('template',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('schema', sa.JSON(), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_category'), 'template', ['category'], unique=False)
    op.create_index(op.f('ix_template_name'), 'template', ['name'], unique=True)
    op.create_table('draft',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('template_name', sa.String(length=128), nullable=False),
    sa.Column('style', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.String(length=64), nullable=True),
    sa.Column('root_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('input_payload', sa.JSON(), nullable=False),
    sa.Column('revision_instruction', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draft_parent_id'), 'draft', ['parent_id'], unique=False)
    op.create_index(op.f('ix_draft_root_id'), 'draft', ['root_id'], unique=False)
    op.create_table('draft_element',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('draft_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('verified_status', sa.String(length=32), nullable=False),
    sa.Column('source_ref', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['draft.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draft_element_draft_id'), 'draft_element', ['draft_id'], unique=False)
    op.create_table('fact_check',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('draft_id', sa.String(length=64), nullable=False),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('basis', sa.Text(), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['draft.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fact_check_draft_id'), 'fact_check', ['draft_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fact_check_draft_id'), table_name='fact_check')
    op.drop_table('fact_check')
    op.drop_index(op.f('ix_draft_element_draft_id'), table_name='draft_element')
    op.drop_table('draft_element')
    op.drop_index(op.f('ix_draft_root_id'), table_name='draft')
    op.drop_index(op.f('ix_draft_parent_id'), table_name='draft')
    op.drop_table('draft')
    op.drop_index(op.f('ix_template_name'), table_name='template')
    op.drop_index(op.f('ix_template_category'), table_name='template')
    op.drop_table('template')
    op.drop_table('reference_material')
    op.drop_index(op.f('ix_export_log_draft_id'), table_name='export_log')
    op.drop_table('export_log')
    # ### end Alembic commands ###
